server:
  port: 9090
  tomcat:
    uri-encoding: UTF-8
    accesslog:
      enabled: true
spring:
  profiles:
#    active: prod
    active: dev

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hckk.sql.orderservice.entity
  configuration:
    map-underscore-to-camel-case: true