zookeeper:
  server:
    url: 192.168.155.66:2181

spring:
  datasource:
    url: jdbc:mysql://192.168.154.219:3306/qa_platform_test?characterEncoding=UTF-8&useSSL=false
    username: qaplatform
    password: Helloqa@2017
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.155.150
    port: 6379
    password: Yixin4redis
cas:
  shiro:
    # cas服务器host， 结束不带 /
    server-host: http://test.casserver.yxqiche.com
    # 客户端服务器host， 结束不带 /
    client-host: http://test.order.hckk.com
#    client-host: http://localhost:9090
    # 基础信息服务地址
    user-host:
      - http://crmopenapi.yxqiche.com/baseinfapi
    # 登录成功路径， 默认根目录
    success-url: /
    # 无权限页面路径
    unauthorized-url: /unauthorized
    # shiro 过滤器配置，cas 和 logout 过滤器已经默认添加
    filter-chain-definitions:
      - /unauthorized = anon
      - /logout = anon
      - /swagger-resources/** = anon
      - /swagger-ui.html** = anon
      - /webjars/** = anon
      - /** = user

logging:
  level:
    com.hckk.sgl.orderservice: debug
    com.yixin.crm: debug
#    org.mybatis: debug
    # 调试 javamail
#    com.sun.mail: debug
#    javax.mail: debug